### ISSUE TITLE
Gallery-Option currently does not save chosen picture.

### ISSUE THREAD

**Issue by devcayed** [EverythingUnderCTRL/HTLCatcher#12]
Upon clicking the image button a dialog is called in which the player has to choose how to set his avatar.
a) Take a picture using the device camera
b) Select a picture of the local device camera

However, when selecting a picture from the gallery, it is not set as icon for the image button, nor is it saved as avatar image which means the game cannot be started.

**Comment by bemoty** [comment]
fixed in 597948be6fd5319e81abd8a88df7aedd2939c5ac
