### ISSUE TITLE
Work on the game design

### ISSUE THREAD

**Issue by bemoty** [EverythingUnderCTRL/HTLCatcher#6]
The game currently is super boring — different stages of the app are always reached at the same time and always with the same speed. We need some randomness and variety implemented to make the game more fun to play.

- Make first stage a bit easier
- Randomize stage behaviour
- Other difficulties?
- Catchable buff logos (which maybe grant a shield for a short duration or bonus points?)
- Implement your own ideas

Keep in mind that we might one day add some kind of shop where players can use score points to buy buffs or something. (Don't make scored points worthless!)

**Comment by devcayed** [comment]
Stages now start at random times.

**Comment by bemoty** [comment]
Started implementing new logos as per #19
