### ISSUE TITLE
Implement local leaderboard

### ISSUE THREAD

**Issue by bemoty** [EverythingUnderCTRL/HTLCatcher#7]
The PlayStore version should get a local leaderboard for players to save their personal high scores to

**Comment by bemoty** [comment]
Remote leaderboard added in /server/ subdirectory.
https://github.com/htl-anichstrasse/htl-catcher/tree/master/server

**Comment by devcayed** [comment]
Implementation of remote leaderboard is finished.

**Comment by bemoty** [comment]
Local leaderboard is no longer needed
